server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://39.107.228.75:3306/xy365?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: uAiqwVwjJ8-i
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: redis
xy:
  config:
    file-config:
      temp-dir: /file/temp/
      image-server: http://image.luosen365.com/
    wx-config:
      app-id: wx886da5540ca9dba4
      secret: 373b3e68734368a0d4ff76403d213da3

